resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    server_name _;
    location / {
        set $upstream_api http://api:8000;
        proxy_pass $upstream_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}